server.port=8080
spring.devtools.add-properties=false

# Database Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/citacita_schema?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=tm04user
spring.datasource.password=TM04_Passw0rd!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Connection Pool Settings
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.connection-timeout=30000

# MyBatis Specific Settings
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/*.xml

# Azure OpenAI Service Configuration
azure.openai.endpoint=https://zyan0-mejy4iwr-japaneast.services.ai.azure.com
azure.openai.apiKey=5zTBpihxgcNSa7phRIzjM97Ruf8nGfgpbo0V0i8mSx3rB57Rtq9JJQQJ99BHACi0881XJ3w3AAAAACOGvs4X

# Logging Configuration
logging.level.com.citacita=DEBUG
logging.level.com.citacita.mapper=TRACE
logging.level.com.zaxxer.hikari=DEBUG

# For Productive Environments
#logging.level.com.citacita=INFO
#logging.level.com.zaxxer.hikari=INFO
#logging.level.org.mybatis=INFO